# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# If you are using Rails 5.2 or newer, consider using the
# encrypted credentials feature described here:
# http://edgeguides.rubyonrails.org/security.html#custom-credentials

default: &default
  #admin_name: <%= ENV.fetch("MAIL_ADMIN_NAME") { "First User" } %>
  #admin_email: <%= ENV.fetch("MAIL_ADMIN_EMAIL") { "user@example.com" } %>
  #admin_password: <%= ENV.fetch("MAIL_ADMIN_PASSWORD") { "changeme" } %>
  domain_name: <%= ENV.fetch("MAIL_DOMAIN_NAME") { "example.com" } %>
  secret_key_base: <%= ENV.fetch("RAIL_SECRET_KEY_BASE") { "very_long_random_string" } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
